name: 'Get secrets from AWS'
description: 'Securely get secrets from AWS Secrets Manager'

inputs:
  role-to-assume:
    description: 'Which role to use to retrieve secrets'
    required: true
  secret-ids:
    description: 'Which secrets to get'
    required: true
  region:
    description: 'AWS region'
    required: false
    default: 'eu-central-1'

runs:
  using: "composite"
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}
    - name: get secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: ${{ inputs.secret-ids }}
